### ISSUE TITLE
ERROR: Command errored out with exit status 1

### ISSUE THREAD

**Issue by cloudycloudsinheaven** [cathalgarvey/rssfilter#2]
Hey there,

I wanted to try some modules in python and install them with pip.

I always get: 
**"ERROR: Command errored out with exit status 1"**

whenever I do: 
**"pip 3 install pandas"**

Environment: Windows 10, pip 20.2.4, Python 3.9.0

Could somebody please help me? Cannot solve this problem for hours..

Cheers,
Oli

**Comment by cathalgarvey** [comment]
Bit confused here: is pandas a dependency of `rssfilter` or are you just looking for advice on Python generally, here?

There are other forums for general Python support that are more appropriate than the issue tracker of an unmaintained spare-time project.

In any case, at a glance you may be using the wrong command: it's not `pip 3`, it's `pip3`.

In case this helps focus your efforts: "exit status 1" is also not informative: it's a Unix (ergo, Linux) convention that when a command succeeds, it returns "0", but any other issue is a failure. However, these days people generally do not return anything _except_ 1, just to let the shell know something broke. If no other useful information was provided then "error 1" sadly does not help.

Beyond that I'm afraid I can't help much: Windows is generally a poor development platform and it's full of problems that I haven't ever experienced and therefore can't offer help with. I would suggest looking for a better forum.

**Comment by cloudycloudsinheaven** [comment]
Thank you for your time. I see there is alot to do for me :) Could it be that Anaconda works better with any python packages?
